### ISSUE TITLE
Wrong action in routes configuration 

### ISSUE THREAD

**Issue by tflori** [FloKnapp/faulancer-kickstart#1]
https://github.com/FloKnapp/faulancer-kickstart/blob/57597d8429194ee1d69a2a947bebf8da35d0ea94/config/routes.conf.php#L33

shouldn't this be the article action?

**Comment by FloKnapp** [comment]
Thank you very much for your contribution ;-). You're right, i fixed it with the commit 5878ff84d16c465590e2b66511696abf0e814ebe
